### ISSUE TITLE
기능들 리팩토링

### ISSUE THREAD

**Issue by HeoJoonSeo** [prgrms-be-devcourse/NBE2-3-1-team7#59]
## 📝 리팩터링 설명

> 업데이트와 입력부분을 리팩토링할려고합니다

## 🎯 리팩터링 목표

> 수업에 배운 내용 활용하기
## 🔄 리팩터링 방법

일단 
> String문자열로 비교하지않고  result 반환값으로 서비스 로직에서 에러를 던져서 위임하고 컨트롤러에서 처리하는 방식으로 바꿔볼려고합니다

**Comment by DongminL** [comment]
무슨 기능을 리팩터링하는지 상세히 기술해주세요
